package ca.cgjennings.apps.librivox.tools;

import java.awt.Frame;

import static ca.cgjennings.apps.librivox.Checker.string;

/**
 * A dialog that displays errors encountered by a file processor.
 *
 * @author Christopher G. Jennings https://cgjennings.ca/contact/
 * @since 0.92
 */
class ProcessingErrorDialog extends javax.swing.JDialog {

    /**
     * Creates new form ProcessingErrorDialog
     */
    public ProcessingErrorDialog(Frame parent, String text) {
        super(parent, true);
        initComponents();
        getRootPane().setDefaultButton(cancelBtn);
        textArea.setText(text);
        textArea.select(0, 0);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText(string("fp-errors")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 8, 6, 8);
        getContentPane().add(jLabel1, gridBagConstraints);

        textArea.setColumns(40);
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setRows(4);
        textArea.setTabSize(4);
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 8);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        cancelBtn.setText(string("close")); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 8, 8);
        getContentPane().add(cancelBtn, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cancelBtnActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_cancelBtnActionPerformed
            dispose();
	}//GEN-LAST:event_cancelBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
